DATASET_DIR = './dataset'
RESULTS_DIR = './results'
LEFT_KEYS = ('LeftX', 'LeftY')
RIGHT_KEYS = ('RightX', 'RightY')


LSTM_LAYERS = 1
N_FEATURES = 63
OUTPUT_SIZE = 1
DROPOUT = 0.5
BATCH_SIZE = 256
DETECTIONS_BEFORE = 2
DETECTIONS_AFTER = 1
N_STEPS = DETECTIONS_BEFORE + 1 + DETECTIONS_AFTER
EPOCHS = 305
CALLBACKS_PERIOD = 50
DATA_AUGMENTATION = True
DATA_AUGMENTATION_RATIO = 0.75
DATA_AUG_X_SLIDE_RATIO = 0.3#0.3
DATA_AUG_Y_SLIDE_RATIO = 0.3#0.3
DATA_AUG_Z_SLIDE_RATIO = 0.5#0.5

# Slight noise applies between parts of the hand
SLIGHT_NOISE_X = 0.0025
SLIGHT_NOISE_Y = 0.0025
SLIGHT_NOISE_Z = 0.0005

# Hard noise applies between frames
HARD_NOISE_X = 0.01
HARD_NOISE_Y = 0.01
HARD_NOISE_Z = 0.0025