DATASET_DIR = './dataset'
RESULTS_DIR = './results'
LEFT_KEYS = ('LeftX', 'LeftY')
RIGHT_KEYS = ('RightX', 'RightY')


LSTM_LAYERS = 1
N_FEATURES = 63
HIDDEN_SIZE = 16
OUTPUT_SIZE = 1
DROPOUT = 0.8
BATCH_SIZE = 256
DETECTIONS_BEFORE = 2
DETECTIONS_AFTER = 1
N_STEPS = DETECTIONS_BEFORE + 1 + DETECTIONS_AFTER
EPOCHS = 1000
CALLBACKS_PERIOD = 50
DATA_AUGMENTATION = True
DATA_AUGMENTATION_RATIO = 0.4